//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoKiemKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoKiemKe()
        {
            this.KiemKeHangHoas = new HashSet<KiemKeHangHoa>();
        }
    
        public long ID_BaoCao { get; set; }
        public long ID_User { get; set; }
        public string TenKhuVuc { get; set; }
        public string ID_Kho { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> TrangThaiLuu { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiemKeHangHoa> KiemKeHangHoas { get; set; }
    }
}
