//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarcodeEntities : DbContext
    {
        public BarcodeEntities()
            : base("name=BarcodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<KiemKeHangHoa> KiemKeHangHoas { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
