//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuaHang()
        {
            this.Khoes = new HashSet<Kho>();
            this.KeHangs = new HashSet<KeHang>();
        }
    
        public string MaCH { get; set; }
        public string MaKhuVuc { get; set; }
        public string MaGoiNho { get; set; }
        public string TenCH { get; set; }
        public string TenGiaoDich { get; set; }
        public string KyTuPhatSinhMa { get; set; }
        public string DiaChi { get; set; }
        public string MST { get; set; }
        public string SoDienThoai { get; set; }
        public string MaNVTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNVCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> LaCHTT { get; set; }
        public string WebSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kho> Khoes { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHang> KeHangs { get; set; }
    }
}
