//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public long ID { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<long> ID_Users { get; set; }
        public string Status { get; set; }
        public string IDThietBi { get; set; }
    
        public virtual User User { get; set; }
    }
}
