//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyetHangHoa
    {
        public long ID { get; set; }
        public long STT { get; set; }
        public Nullable<long> IDUser { get; set; }
        public string IDKho { get; set; }
        public string IDHangHoa { get; set; }
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string TenKeHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public Nullable<int> LoaiKiemKe { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> Luu { get; set; }
    }
}
