//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.KiemKeHangHoas = new HashSet<KiemKeHangHoa>();
        }
    
        public string HangHoaID { get; set; }
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string MaGoiNho { get; set; }
        public string MaCu { get; set; }
        public string MaKeHang { get; set; }
        public string MaNCC { get; set; }
        public string MaNganh { get; set; }
        public string MaNhom { get; set; }
        public string MaPhanNhom { get; set; }
        public string MaPLU { get; set; }
        public decimal VATDauVao { get; set; }
        public decimal VATDauRa { get; set; }
        public decimal GiaVon { get; set; }
        public string MaNVTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNVCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> LoaiHangHoa { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> CapDo { get; set; }
        public Nullable<int> HienThiTrongDanhMuc { get; set; }
        public bool HangCanKy { get; set; }
        public bool MaTam { get; set; }
        public Nullable<bool> DaDongBo { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public Nullable<long> STT { get; set; }
        public Nullable<bool> DaHuy { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public Nullable<int> MaPLHang { get; set; }
        public bool GiaTamTinh { get; set; }
    
        public virtual NganhHang NganhHang { get; set; }
        public virtual NhomHang NhomHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiemKeHangHoa> KiemKeHangHoas { get; set; }
        public virtual PLU PLU { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual PhanNhomHang PhanNhomHang { get; set; }
        public virtual KeHang KeHang { get; set; }
    }
}
