//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public string MaKho { get; set; }
        public string MaGoiNho { get; set; }
        public int STT { get; set; }
        public string MaCH { get; set; }
        public string TenKho { get; set; }
        public string TenGiaoDich { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string MaNVTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNVCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<bool> LaKhoKM { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
    }
}
