//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemKeHangHoa
    {
        public long ID { get; set; }
        public Nullable<long> ID_Users { get; set; }
        public string ID_Kho { get; set; }
        public string ID_HangHoa { get; set; }
        public string TenKeHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> LoaiKiemKe { get; set; }
        public Nullable<long> ID_BaoCao { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual BaoCaoKiemKe BaoCaoKiemKe { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual User User { get; set; }
    }
}
