//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public string MaNCC { get; set; }
        public string MaGoiNho { get; set; }
        public string TenNCC { get; set; }
        public string TenGiaoDich { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string MaSoThue { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
        public string MaNVTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNVCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> STT { get; set; }
        public string SoTaiKhoan { get; set; }
        public string MaNganHang { get; set; }
        public Nullable<int> ThuocCongTy { get; set; }
        public string NguoiDaiDien { get; set; }
        public string MaPTCT { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<decimal> TLCKDaiLy { get; set; }
        public Nullable<bool> isKhoaNhaCungCap { get; set; }
        public Nullable<bool> LaNCCKyGui { get; set; }
        public Nullable<decimal> TLHH { get; set; }
        public Nullable<bool> ChiTraGiaVon { get; set; }
        public Nullable<bool> ChiTraGiaBan { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
