//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcocde
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanNhomHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanNhomHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public string MaPhanNhom { get; set; }
        public int STT { get; set; }
        public string MaNhom { get; set; }
        public string MaNganh { get; set; }
        public string TenPhanNhom { get; set; }
        public string MaGoiNho { get; set; }
        public string MoTa { get; set; }
        public string MaNVNhap { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNVCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
